### ISSUE TITLE
Update pause and play button and split play/reset from time control

### ISSUE THREAD

**Issue by EwoutH** [Corvince/mesa-interactive#5]
Hi! 

This is really awesome work, being able to step back in time and hover over agents to get their current states is incredibly useful. Brings it up to par with NetLogo for the most part!

One nitpick: I find the pause play button not extremely intuitive. I first thought I needed to press the "forward to end" button. Maybe we can split the play and reset buttons from the other ones, because:
- Play and reset manipulates the model (initializes and steps)
- The step forward/back buttons modify the current step viewed/loaded, and allow going back and forth between existing steps.

![Screenshot_288](https://github.com/Corvince/mesa-interactive/assets/15776622/c0923fc4-efb9-4290-ae28-0b311504db48)

**Comment by Corvince** [comment]
That's a great idea, splitting the buttons. Because yes, even for me it is not very intuitive. 

Additionally we should disable buttons when they are currently without any effect. So for example skip to end can be deactivated initially because we are already at the end and users can't press them in the hope of starting the simulation

**Comment by EwoutH** [comment]
Deactivating is a great idea! Can we visually grey them out?

**Comment by Corvince** [comment]
Done, it now looks something like this! 

![image](https://github.com/Corvince/mesa-interactive/assets/13568919/523200a9-1161-4859-af73-621242879cf5)

**Comment by EwoutH** [comment]
Looks great, already feels more intuitive.

Also excited you're working on it again!
